zuul:
  routes:
    api-service:
      path: /as/**
      serviceId: api-service

api-service:
  ribbon.ReadTimeout: 10000

hystrix:
  command:
    api-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
